UPSTREAM: ASoC: Intel: sof-rt5682: fix undefined references with Baytrail-only support
The sof-rt5682 machine driver supports both legacy Baytrail devices
and more recent ApolloLake/CometLake platforms. When only Baytrail is
selected, the compilation fails with the following errors:

ERROR: "hdac_hdmi_jack_port_init"
[sound/soc/intel/boards/snd-soc-sof_rt5682.ko] undefined!

ERROR: "hdac_hdmi_jack_init"
[sound/soc/intel/boards/snd-soc-sof_rt5682.ko] undefined!

Fix by selecting SND_SOC_HDAC_HDMI unconditionally. The code for HDMI
support is not reachable on Baytrail so this change has no functional
impact.

Fixes: f70abd75b7c6 ("ASoC: Intel: add sof-rt5682 machine driver")
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 17fc24875da1bef4650cf007edae3b2e26d2fa4e)

BUG=b:987654321
TEST=Test Audio use cases for CML with full SOF patch series applied.

Change-Id: I10b78830497c34be9934ece71a53705ed550732e
Signed-off-by: Ap, Kamal <kamal.ap@intel.corp-partner.google.com>